### PR TITLE
Week3

### PR DESCRIPTION
**Pull request by MzCorona**

### CODE REVIEW

**Review by jolsenvaldez — APPROVED** [review]
I didn't make individual comments within your Week3 file because the file wasn't loading properly on my end, BUT: 
-I thought you did a great job of introducing the concepts for the problem set, as well as the background code 
-I like all of the photos and descriptions you include 
-Your breakdown of the code and your explanations of what you're doing, why, how, etc. are super helpful and make this much more accessible to a beginner coder audience. 

Nice job!

**Comment by vaga3461** [comment]
Overall, looks really good!

**Comment by MzCorona** [comment]
<p>That's a fair point. I'll uncomment them. Thanks!</p>

---

 <a href='https://app.reviewnb.com/CUB-Computational-Tools/2020-ps-MzCorona/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MzCorona** [comment]
<p>Oooh yeah! Good idea! I'll see if I can do that quickly. Thanks!</p>

---

 <a href='https://app.reviewnb.com/CUB-Computational-Tools/2020-ps-MzCorona/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MzCorona** [comment]
<p>Genius! I had to look at the draft to understand what you meant, but it makes sense now. I appreciate the comment, I updated it. Thanks!</p>

---

 <a href='https://app.reviewnb.com/CUB-Computational-Tools/2020-ps-MzCorona/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MzCorona** [comment]
Merging pull request with final week 3 problem set and KEY.

**Pull request merged**
